function plot_figure_5_6()

clc;
close all;

[file15, path15] = uigetfile( ...
    {'*.csv','CSV files (*.csv)'}, ...
    'Select 15 September sensor data');

if isequal(file15,0)
    disp('15 September file selection cancelled.');
    return;
end

full15 = fullfile(path15,file15);

[file16, path16] = uigetfile( ...
    {'*.csv','CSV files (*.csv)'}, ...
    'Select 16 September sensor data');

if isequal(file16,0)
    disp('16 September file selection cancelled.');
    return;
end

full16 = fullfile(path16,file16);

fprintf('\nSelected files:\n');
fprintf('15 Sep: %s\n',full15);
fprintf('16 Sep: %s\n\n',full16);

ID_D = 1549410049;

T15 = readSensorFile(full15);

T16 = readSensorFile(full16);

T = [T15; T16];

requiredFields = { ...
    'receive_time', ...
    'node_id', ...
    'temperature_c'};

for k = 1:numel(requiredFields)

    if ~ismember(requiredFields{k},T.Properties.VariableNames)

        error( ...
            'Required field "%s" was not found.', ...
            requiredFields{k});

    end

end

T.receive_dt = parseReceiveTime(T.receive_time);

if isnumeric(T.node_id)

    T.node_id_num = double(T.node_id);

else

    T.node_id_num = str2double(string(T.node_id));

end

if isnumeric(T.temperature_c)

    T.temperature_num = double(T.temperature_c);

else

    T.temperature_num = str2double(string(T.temperature_c));

end

D = T( ...
    T.node_id_num == ID_D & ...
    ~isnat(T.receive_dt) & ...
    isfinite(T.temperature_num), :);

if isempty(D)
    error('No valid Sensor D observations were found.');
end

D = sortrows(D,'receive_dt');

D.trailing5 = movmean( ...
    D.temperature_num, ...
    [4 0], ...
    'omitnan');

plotStart = datetime(2026,9,15,23,25,0);
plotEnd   = datetime(2026,9,16,0,30,0);

W = D( ...
    D.receive_dt >= plotStart & ...
    D.receive_dt <= plotEnd, :);

if isempty(W)

    error([ ...
        'No Sensor D records were found between ' ...
        '15 Sep 23:25 and 16 Sep 00:30.']);

end

thresholdC = 2.0;

rawCross = find( ...
    W.temperature_num <= thresholdC, ...
    1, ...
    'first');

smoothCross = find( ...
    W.trailing5 <= thresholdC, ...
    1, ...
    'first');

fprintf('FIGURE 5.6 ANALYSIS\n');
fprintf('====================================================\n');

fprintf('Plot start : %s\n', ...
    datestr(W.receive_dt(1),'yyyy-mm-dd HH:MM:SS.FFF'));

fprintf('Plot end   : %s\n', ...
    datestr(W.receive_dt(end),'yyyy-mm-dd HH:MM:SS.FFF'));

if ~isempty(rawCross)

    fprintf('Raw D first <= 2 degC      : %s, %.2f degC\n', ...
        datestr( ...
        W.receive_dt(rawCross), ...
        'yyyy-mm-dd HH:MM:SS.FFF'), ...
        W.temperature_num(rawCross));

end

if ~isempty(smoothCross)

    fprintf('Trailing-5 first <= 2 degC : %s, %.3f degC\n', ...
        datestr( ...
        W.receive_dt(smoothCross), ...
        'yyyy-mm-dd HH:MM:SS.FFF'), ...
        W.trailing5(smoothCross));

end

fprintf('Minimum raw D temperature  : %.2f degC\n', ...
    min(W.temperature_num));

fig = figure( ...
    'Color','w', ...
    'Units','pixels', ...
    'Position',[100 100 950 480]);

ax = axes(fig);

hold(ax,'on');

hRaw = plot( ...
    ax, ...
    W.receive_dt, ...
    W.temperature_num, ...
    '-', ...
    'Color',[0.65 0.65 0.65], ...
    'LineWidth',1.5, ...
    'DisplayName','Raw D');

hSmooth = plot( ...
    ax, ...
    W.receive_dt, ...
    W.trailing5, ...
    '-', ...
    'Color',[0.50 0.30 0.70], ...
    'LineWidth',1.8, ...
    'DisplayName','Trailing five readings');

hThreshold = yline( ...
    ax, ...
    thresholdC, ...
    '--', ...
    'Color',[0.25 0.25 0.25], ...
    'LineWidth',1.8, ...
    'DisplayName','2 °C screening threshold');

xlim(ax,[plotStart plotEnd]);

yMin = min([ ...
    W.temperature_num; ...
    W.trailing5]);

yMax = max([ ...
    W.temperature_num; ...
    W.trailing5]);

ylim(ax,[ ...
    floor(yMin)-2, ...
    ceil(yMax)+2]);

tickTimes = [ ...
    datetime(2026,9,15,23,30,0), ...
    datetime(2026,9,15,23,45,0), ...
    datetime(2026,9,16,0,0,0), ...
    datetime(2026,9,16,0,15,0), ...
    datetime(2026,9,16,0,30,0) ];

ax.XTick = tickTimes;

ax.XTickLabel = { ...
    '23:30', ...
    '23:45', ...
    '00:00', ...
    '00:15', ...
    '00:30' };

ylabel( ...
    ax, ...
    'Temperature (°C)', ...
    'FontName','Times New Roman', ...
    'FontSize',14);

xlabel( ...
    ax, ...
    '15–16 September 2026 \bullet gateway clock', ...
    'FontName','Times New Roman', ...
    'FontSize',13);

ax.FontName = 'Times New Roman';
ax.FontSize = 12;
ax.LineWidth = 1;

grid(ax,'on');

ax.GridAlpha = 0.16;

box(ax,'off');

legend( ...
    ax, ...
    [hRaw hSmooth hThreshold], ...
    { ...
    'Raw D', ...
    'Trailing five readings', ...
    '2 °C screening threshold' ...
    }, ...
    'Location','southwest', ...
    'FontName','Times New Roman', ...
    'FontSize',11, ...
    'Box','on');

try
    ax.XAxis.SecondaryLabel.Visible = 'off';
catch
end

pngFile = fullfile( ...
    path16, ...
    'Figure_5_6_Raw_and_Trailing_D.png');

pdfFile = fullfile( ...
    path16, ...
    'Figure_5_6_Raw_and_Trailing_D.pdf');

exportgraphics( ...
    fig, ...
    pngFile, ...
    'Resolution',600);

exportgraphics( ...
    fig, ...
    pdfFile, ...
    'ContentType','vector');

fprintf('\n');
fprintf('FIGURE EXPORTED\n');
fprintf('====================================================\n');

fprintf('PNG:\n%s\n\n',pngFile);

fprintf('PDF:\n%s\n\n',pdfFile);

fprintf('Done.\n');

end

function T = readSensorFile(filename)

opts = detectImportOptions( ...
    filename, ...
    'TextType','string', ...
    'VariableNamingRule','preserve');

if ismember('receive_time',opts.VariableNames)

    opts = setvartype( ...
        opts, ...
        'receive_time', ...
        'string');

end

T = readtable(filename,opts);

end

function dt = parseReceiveTime(raw)

if isdatetime(raw)

    dt = raw;
    return;

end

s = string(raw);

s = strtrim(s);

dt = NaT(size(s));

for i = 1:numel(s)

    if strlength(s(i)) == 0 || ismissing(s(i))
        continue;
    end

    try

        dt(i) = datetime( ...
            s(i), ...
            'InputFormat', ...
            'yyyy-MM-dd''T''HH:mm:ss.SSS');

        continue;

    catch
    end

    try

        dt(i) = datetime( ...
            s(i), ...
            'InputFormat', ...
            'yyyy-MM-dd HH:mm:ss.SSS');

        continue;

    catch
    end

    try

        dt(i) = datetime(s(i));

    catch

        dt(i) = NaT;

    end

end

end
