function plot_figure_5_4_multihop()

clc;
close all;

[fileName, filePath] = uigetfile( ...
    {'*.csv;*.xlsx;*.xls', ...
     'Multi-hop data (*.csv, *.xlsx, *.xls)'}, ...
    'Select the multi-hop experiment file');

if isequal(fileName,0)
    disp('File selection cancelled.');
    return;
end

fullFile = fullfile(filePath,fileName);

fprintf('\nSelected file:\n%s\n\n',fullFile);

ID_A = 1623979917;
ID_B = 1611764737;
ID_D = 1549410049;

T = smartReadMultiHopFile(fullFile);

requiredFields = { ...
    'receive_time', ...
    'node_id', ...
    'sequence', ...
    'uptime_ms'};

for k = 1:numel(requiredFields)

    if ~ismember(requiredFields{k},T.Properties.VariableNames)

        error( ...
            'Required field "%s" is missing.', ...
            requiredFields{k});

    end

end

T.receive_dt = parseReceiveTime(T.receive_time);

T.node_id_num  = toNumeric(T.node_id);
T.sequence_num = toNumeric(T.sequence);
T.uptime_num   = toNumeric(T.uptime_ms);

valid = ...
    ~isnat(T.receive_dt) & ...
    isfinite(T.node_id_num) & ...
    isfinite(T.sequence_num) & ...
    isfinite(T.uptime_num);

T = T(valid,:);

T = sortrows(T,'receive_dt');

A = T(T.node_id_num == ID_A,:);
B = T(T.node_id_num == ID_B,:);
D = T(T.node_id_num == ID_D,:);

A = sortrows(A,'receive_dt');
B = sortrows(B,'receive_dt');
D = sortrows(D,'receive_dt');

fprintf('MULTI-HOP DATA SUMMARY\n');
fprintf('====================================================\n');
fprintf('A records : %d\n',height(A));
fprintf('B records : %d\n',height(B));
fprintf('D records : %d\n',height(D));
fprintf('Total     : %d\n\n',height(T));

A_restart_idx = find( ...
    diff(A.sequence_num) < 0 & ...
    diff(A.uptime_num) < 0, ...
    1, ...
    'first');

if isempty(A_restart_idx)

    error('No A restart was detected; P5 cannot be identified.');

end

A_P5_start_idx = A_restart_idx + 1;

A_P5_start = A.receive_dt(A_P5_start_idx);

A_first = A(1:A_restart_idx,:);

A_direct = A(A_P5_start_idx:end,:);

A_dt = seconds(diff(A_first.receive_dt));

[gapSeconds, gapIndex] = max(A_dt);

gapStart = A_first.receive_dt(gapIndex);
gapEnd   = A_first.receive_dt(gapIndex + 1);

seqBeforeGap = A_first.sequence_num(gapIndex);
seqAfterGap  = A_first.sequence_num(gapIndex + 1);

missingA = ...
    seqAfterGap - seqBeforeGap - 1;

P1_start = D.receive_dt(1);

P2_start = A_first.receive_dt(1);

P3_start = gapStart;

P4_start = gapEnd;

P5_start = A_P5_start;

P4_end = A_first.receive_dt(end);

P5_end = A_direct.receive_dt(end);

fprintf('PHASE INFORMATION\n');
fprintf('====================================================\n');

fprintf('P1 start : %s\n', ...
    datestr(P1_start,'yyyy-mm-dd HH:MM:SS.FFF'));

fprintf('P2 start : %s\n', ...
    datestr(P2_start,'yyyy-mm-dd HH:MM:SS.FFF'));

fprintf('P3 start : %s\n', ...
    datestr(P3_start,'yyyy-mm-dd HH:MM:SS.FFF'));

fprintf('P4 start : %s\n', ...
    datestr(P4_start,'yyyy-mm-dd HH:MM:SS.FFF'));

fprintf('P5 start : %s\n\n', ...
    datestr(P5_start,'yyyy-mm-dd HH:MM:SS.FFF'));

fprintf('A last reception before gap:\n');
fprintf('  Sequence = %d\n',seqBeforeGap);
fprintf('  Time     = %s\n\n', ...
    datestr(gapStart,'yyyy-mm-dd HH:MM:SS.FFF'));

fprintf('A first reception after gap:\n');
fprintf('  Sequence = %d\n',seqAfterGap);
fprintf('  Time     = %s\n\n', ...
    datestr(gapEnd,'yyyy-mm-dd HH:MM:SS.FFF'));

fprintf('A reception gap = %.3f s\n',gapSeconds);
fprintf('Absent A sequence positions = %d\n\n',missingA);

fprintf('CHECK AGAINST THESIS RESULT\n');
fprintf('====================================================\n');

if abs(gapSeconds - 400.006) < 0.001
    fprintf('Reception gap : MATCH (400.006 s)\n');
else
    fprintf('Reception gap : DIFFERENT (%.3f s)\n',gapSeconds);
end

if missingA == 79
    fprintf('Missing A sequences : MATCH (79)\n');
else
    fprintf('Missing A sequences : DIFFERENT (%d)\n',missingA);
end

plotStart = T.receive_dt(1) - minutes(3);
plotEnd   = T.receive_dt(end) + minutes(3);

fig = figure( ...
    'Color','w', ...
    'Units','pixels', ...
    'Position',[100 50 1000 820]);

tl = tiledlayout( ...
    fig, ...
    3,1, ...
    'TileSpacing','compact', ...
    'Padding','compact');

colourA = [0.0000 0.4470 0.7410];
colourB = [0.8500 0.3250 0.0980];
colourD = [0.4940 0.1840 0.5560];

gapColour = [0.95 0.82 0.75];

phaseColour = [0.96 0.96 0.96];

ax1 = nexttile(tl,1);

hold(ax1,'on');

addPhaseBackgrounds( ...
    ax1, ...
    P1_start, ...
    P2_start, ...
    P3_start, ...
    P4_start, ...
    P4_end, ...
    P5_start, ...
    P5_end, ...
    gapStart, ...
    gapEnd, ...
    phaseColour, ...
    gapColour);

plot( ...
    ax1, ...
    A.receive_dt, ...
    A.sequence_num, ...
    '.', ...
    'Color',colourA, ...
    'MarkerSize',8);

ylabel(ax1,'A sequence');

xlim(ax1,[plotStart plotEnd]);

grid(ax1,'on');
ax1.GridAlpha = 0.15;

box(ax1,'off');

ax1.FontName = 'Times New Roman';
ax1.FontSize = 12;

yl = ylim(ax1);

phaseLabelY = ...
    yl(2) + 0.04*(yl(2)-yl(1));

phaseCenters = [ ...
    P1_start + (P2_start-P1_start)/2, ...
    P2_start + (P3_start-P2_start)/2, ...
    P3_start + (P4_start-P3_start)/2, ...
    P4_start + (P4_end-P4_start)/2, ...
    P5_start + (P5_end-P5_start)/2 ];

phaseNames = {'P1','P2','P3','P4','P5'};

for k = 1:5

    text( ...
        ax1, ...
        phaseCenters(k), ...
        phaseLabelY, ...
        phaseNames{k}, ...
        'HorizontalAlignment','center', ...
        'VerticalAlignment','bottom', ...
        'FontName','Times New Roman', ...
        'FontSize',13, ...
        'Clipping','off');

end

ax2 = nexttile(tl,2);

hold(ax2,'on');

addPhaseBackgrounds( ...
    ax2, ...
    P1_start, ...
    P2_start, ...
    P3_start, ...
    P4_start, ...
    P4_end, ...
    P5_start, ...
    P5_end, ...
    gapStart, ...
    gapEnd, ...
    phaseColour, ...
    gapColour);

plot( ...
    ax2, ...
    B.receive_dt, ...
    B.sequence_num, ...
    '.', ...
    'Color',colourB, ...
    'MarkerSize',8);

ylabel(ax2,'B sequence');

xlim(ax2,[plotStart plotEnd]);

grid(ax2,'on');
ax2.GridAlpha = 0.15;

box(ax2,'off');

ax2.FontName = 'Times New Roman';
ax2.FontSize = 12;

ax3 = nexttile(tl,3);

hold(ax3,'on');

addPhaseBackgrounds( ...
    ax3, ...
    P1_start, ...
    P2_start, ...
    P3_start, ...
    P4_start, ...
    P4_end, ...
    P5_start, ...
    P5_end, ...
    gapStart, ...
    gapEnd, ...
    phaseColour, ...
    gapColour);

plot( ...
    ax3, ...
    D.receive_dt, ...
    D.sequence_num, ...
    '.', ...
    'Color',colourD, ...
    'MarkerSize',8);

ylabel(ax3,'D sequence');

xlim(ax3,[plotStart plotEnd]);

grid(ax3,'on');
ax3.GridAlpha = 0.15;

box(ax3,'off');

ax3.FontName = 'Times New Roman';
ax3.FontSize = 12;

axesList = [ax1 ax2 ax3];

boundaryTimes = [ ...
    P1_start ...
    P2_start ...
    P3_start ...
    P4_start ...
    P5_start ];

for ax = axesList

    for k = 1:numel(boundaryTimes)

        xline( ...
            ax, ...
            boundaryTimes(k), ...
            ':', ...
            'Color',[0.4 0.4 0.4], ...
            'LineWidth',1.0, ...
            'HandleVisibility','off');

    end

end

ax1.XTickLabel = [];
ax2.XTickLabel = [];

tickTimes = [ ...
    datetime(2026,9,20,22,30,0), ...
    datetime(2026,9,20,22,40,0), ...
    datetime(2026,9,20,22,50,0), ...
    datetime(2026,9,20,23,0,0), ...
    datetime(2026,9,20,23,10,0) ];

ax3.XTick = tickTimes;

ax3.XTickLabel = { ...
    '22:30', ...
    '22:40', ...
    '22:50', ...
    '23:00', ...
    '23:10' };

xlabel( ...
    ax3, ...
    '20 September 2026 \bullet shaded interval bounded by A receptions', ...
    'FontName','Times New Roman', ...
    'FontSize',12);

ax1.XTick = tickTimes;
ax2.XTick = tickTimes;

linkaxes([ax1 ax2 ax3],'x');

try
    ax1.XAxis.SecondaryLabel.Visible = 'off';
    ax2.XAxis.SecondaryLabel.Visible = 'off';
    ax3.XAxis.SecondaryLabel.Visible = 'off';
catch
end

pngFile = fullfile( ...
    filePath, ...
    'Figure_5_4_Multihop_Sequence_Receptions.png');

pdfFile = fullfile( ...
    filePath, ...
    'Figure_5_4_Multihop_Sequence_Receptions.pdf');

exportgraphics( ...
    fig, ...
    pngFile, ...
    'Resolution',600);

exportgraphics( ...
    fig, ...
    pdfFile, ...
    'ContentType','vector');

fprintf('\nFIGURE EXPORTED\n');
fprintf('====================================================\n');

fprintf('PNG:\n%s\n\n',pngFile);
fprintf('PDF:\n%s\n',pdfFile);

end

function T = smartReadMultiHopFile(filename)

fid = fopen(filename,'r');

if fid < 0
    error('Cannot open file.');
end

signature = fread(fid,4,'uint8=>uint8')';
fclose(fid);

isOOXML = ...
    numel(signature) >= 2 && ...
    signature(1) == 80 && ...
    signature(2) == 75;

if isOOXML

    tempFile = [tempname '.xlsx'];

    copyfile(filename,tempFile);

    cleaner = onCleanup( ...
        @() deleteIfExists(tempFile));

    T = readtable( ...
        tempFile, ...
        'FileType','spreadsheet', ...
        'VariableNamingRule','preserve');

else

    opts = detectImportOptions( ...
        filename, ...
        'TextType','string', ...
        'VariableNamingRule','preserve');

    T = readtable(filename,opts);

end

end

function dt = parseReceiveTime(raw)

if isdatetime(raw)

    dt = raw;
    return;

end

s = string(raw);

dt = datetime( ...
    s, ...
    'InputFormat','yyyy-MM-dd''T''HH:mm:ss.SSS');

end

function x = toNumeric(v)

if isnumeric(v)

    x = double(v);

else

    x = str2double(string(v));

end

end

function addPhaseBackgrounds( ...
    ax, ...
    P1_start, ...
    P2_start, ...
    P3_start, ...
    P4_start, ...
    P4_end, ...
    P5_start, ...
    P5_end, ...
    gapStart, ...
    gapEnd, ...
    normalColour, ...
    gapColour)

yl = ylim(ax);

toNum = @(t) datenum(t);

patch( ...
    ax, ...
    [toNum(P1_start) toNum(P2_start) ...
     toNum(P2_start) toNum(P1_start)], ...
    [yl(1) yl(1) yl(2) yl(2)], ...
    normalColour, ...
    'EdgeColor','none', ...
    'FaceAlpha',0.35, ...
    'HandleVisibility','off');

patch( ...
    ax, ...
    [toNum(P2_start) toNum(P3_start) ...
     toNum(P3_start) toNum(P2_start)], ...
    [yl(1) yl(1) yl(2) yl(2)], ...
    normalColour, ...
    'EdgeColor','none', ...
    'FaceAlpha',0.35, ...
    'HandleVisibility','off');

patch( ...
    ax, ...
    [toNum(gapStart) toNum(gapEnd) ...
     toNum(gapEnd) toNum(gapStart)], ...
    [yl(1) yl(1) yl(2) yl(2)], ...
    gapColour, ...
    'EdgeColor','none', ...
    'FaceAlpha',0.55, ...
    'HandleVisibility','off');

patch( ...
    ax, ...
    [toNum(P4_start) toNum(P4_end) ...
     toNum(P4_end) toNum(P4_start)], ...
    [yl(1) yl(1) yl(2) yl(2)], ...
    normalColour, ...
    'EdgeColor','none', ...
    'FaceAlpha',0.35, ...
    'HandleVisibility','off');

patch( ...
    ax, ...
    [toNum(P5_start) toNum(P5_end) ...
     toNum(P5_end) toNum(P5_start)], ...
    [yl(1) yl(1) yl(2) yl(2)], ...
    normalColour, ...
    'EdgeColor','none', ...
    'FaceAlpha',0.35, ...
    'HandleVisibility','off');

end

function deleteIfExists(filename)

if isfile(filename)
    delete(filename);
end

end
