function plot_figure_5_7_gateway_recovery()

clc;
close all;

[monitorFile, monitorPath] = uigetfile( ...
    {'*.csv','CSV files (*.csv)'}, ...
    'Select GATE03_serial_monitor.csv');

if isequal(monitorFile,0)
    disp('File selection cancelled.');
    return;
end

monitorFull = fullfile(monitorPath,monitorFile);

[dataFile, dataPath] = uigetfile( ...
    {'*.csv','CSV files (*.csv)'}, ...
    'Select sensor_data_2026-09-23.csv');

if isequal(dataFile,0)
    disp('File selection cancelled.');
    return;
end

dataFull = fullfile(dataPath,dataFile);

fprintf('\nSelected monitor file:\n%s\n',monitorFull);
fprintf('\nSelected raw-data file:\n%s\n\n',dataFull);

lines = readlines(monitorFull);

lines = lines( ...
    strlength(strtrim(lines)) > 0);

if contains(lower(lines(1)),'timestamp')
    lines = lines(2:end);
end

n = numel(lines);

monitorTime = NaT(n,1);

serialStateText = strings(n,1);
serviceStateText = strings(n,1);

rawLineCount = nan(n,1);
lastSequence = nan(n,1);

for i = 1:n

    parts = split(string(lines(i)),',');

    parts = strtrim(parts);

    if numel(parts) < 5
        continue;
    end

    try

        monitorTime(i) = datetime( ...
            parts(1), ...
            'InputFormat','yyyy-MM-dd HH:mm:ss.SSS');

    catch

        monitorTime(i) = NaT;

    end

    serialStateText(i) = upper(parts(2));
    serviceStateText(i) = lower(parts(3));

    rawLineCount(i) = str2double(parts(4));
    lastSequence(i) = str2double(parts(5));

end

validMonitor = ...
    ~isnat(monitorTime) & ...
    strlength(serialStateText) > 0;

monitorTime = monitorTime(validMonitor);

serialStateText = serialStateText(validMonitor);
serviceStateText = serviceStateText(validMonitor);

rawLineCount = rawLineCount(validMonitor);
lastSequence = lastSequence(validMonitor);

if isempty(monitorTime)
    error('No valid monitor records were found.');
end

serialState = nan(size(serialStateText));

serialState(serialStateText == "PRESENT") = 1;
serialState(serialStateText == "ABSENT")  = 0;

if all(isnan(serialState))
    error('No PRESENT/ABSENT states were detected.');
end

idxFirstAbsent = [];

for i = 2:numel(serialState)

    if serialState(i-1) == 1 && ...
       serialState(i) == 0

        idxFirstAbsent = i;
        break;

    end

end

if isempty(idxFirstAbsent)
    error('No PRESENT -> ABSENT transition was detected.');
end

idxFirstPresentAfter = [];

for i = idxFirstAbsent+1:numel(serialState)

    if serialState(i-1) == 0 && ...
       serialState(i) == 1

        idxFirstPresentAfter = i;
        break;

    end

end

if isempty(idxFirstPresentAfter)
    error('No ABSENT -> PRESENT transition was detected.');
end

idxLastPresentBefore = idxFirstAbsent - 1;
idxLastAbsent = idxFirstPresentAfter - 1;

tLastPresentBefore = ...
    monitorTime(idxLastPresentBefore);

tFirstAbsent = ...
    monitorTime(idxFirstAbsent);

tLastAbsent = ...
    monitorTime(idxLastAbsent);

tFirstPresentAfter = ...
    monitorTime(idxFirstPresentAfter);

outageRows = ...
    idxFirstAbsent:idxLastAbsent;

gatewayActiveThroughout = ...
    all(serviceStateText(outageRows) == "active");

opts = detectImportOptions( ...
    dataFull, ...
    'TextType','string', ...
    'VariableNamingRule','preserve');

T = readtable(dataFull,opts);

requiredFields = { ...
    'receive_time', ...
    'node_id', ...
    'sequence'};

for k = 1:numel(requiredFields)

    if ~ismember( ...
            requiredFields{k}, ...
            T.Properties.VariableNames)

        error( ...
            'Required field "%s" was not found.', ...
            requiredFields{k});

    end

end

rawTimeString = string(T.receive_time);

receiveTime = NaT(height(T),1);

for i = 1:height(T)

    s = strtrim(rawTimeString(i));

    try

        receiveTime(i) = datetime( ...
            s, ...
            'InputFormat', ...
            'yyyy-MM-dd''T''HH:mm:ss.SSS');

    catch

        try

            receiveTime(i) = datetime( ...
                s, ...
                'InputFormat', ...
                'yyyy-MM-dd HH:mm:ss.SSS');

        catch

            receiveTime(i) = NaT;

        end

    end

end

if isnumeric(T.node_id)
    nodeID = double(T.node_id);
else
    nodeID = str2double(string(T.node_id));
end

if isnumeric(T.sequence)
    sequence = double(T.sequence);
else
    sequence = str2double(string(T.sequence));
end

ID_A = 1623979917;

validA = ...
    nodeID == ID_A & ...
    ~isnat(receiveTime) & ...
    isfinite(sequence);

A_time = receiveTime(validA);
A_seq  = sequence(validA);

[A_time,order] = sort(A_time);

A_seq = A_seq(order);

if isempty(A_time)
    error('No Sensor A records were found.');
end

idxLastDataBefore = find( ...
    A_time < tFirstAbsent, ...
    1, ...
    'last');

if isempty(idxLastDataBefore)
    error('No Sensor A record exists before the interruption.');
end

tLastDataBefore = ...
    A_time(idxLastDataBefore);

seqLastBefore = ...
    A_seq(idxLastDataBefore);

idxFirstRecovered = find( ...
    A_time >= tFirstPresentAfter, ...
    1, ...
    'first');

if isempty(idxFirstRecovered)
    error('No Sensor A record exists after serial recovery.');
end

tFirstRecovered = ...
    A_time(idxFirstRecovered);

seqFirstRecovered = ...
    A_seq(idxFirstRecovered);

missingSequences = ...
    seqFirstRecovered - ...
    seqLastBefore - 1;

dataGapSeconds = seconds( ...
    tFirstRecovered - ...
    tLastDataBefore);

recoveryAfterReturnSeconds = seconds( ...
    tFirstRecovered - ...
    tFirstPresentAfter);

confirmedAbsentSeconds = seconds( ...
    tFirstPresentAfter - ...
    tFirstAbsent);

fprintf('\n');
fprintf('========================================================\n');
fprintf('GATE03 SERIAL RECOVERY TEST RESULTS\n');
fprintf('========================================================\n');

fprintf('Last serial PRESENT before loss : %s\n', ...
    datestr( ...
    tLastPresentBefore, ...
    'yyyy-mm-dd HH:MM:SS.FFF'));

fprintf('First serial ABSENT             : %s\n', ...
    datestr( ...
    tFirstAbsent, ...
    'yyyy-mm-dd HH:MM:SS.FFF'));

fprintf('Last serial ABSENT              : %s\n', ...
    datestr( ...
    tLastAbsent, ...
    'yyyy-mm-dd HH:MM:SS.FFF'));

fprintf('First serial PRESENT after      : %s\n', ...
    datestr( ...
    tFirstPresentAfter, ...
    'yyyy-mm-dd HH:MM:SS.FFF'));

fprintf('\n');

fprintf('Last DATA before interruption   : %s\n', ...
    datestr( ...
    tLastDataBefore, ...
    'yyyy-mm-dd HH:MM:SS.FFF'));

fprintf('Sequence                        : %d\n', ...
    seqLastBefore);

fprintf('\n');

fprintf('First recovered DATA            : %s\n', ...
    datestr( ...
    tFirstRecovered, ...
    'yyyy-mm-dd HH:MM:SS.FFF'));

fprintf('Sequence                        : %d\n', ...
    seqFirstRecovered);

fprintf('\n');

fprintf('Missing sequence positions      : %d\n', ...
    missingSequences);

fprintf('DATA reception gap              : %.3f s\n', ...
    dataGapSeconds);

fprintf('Serial device absent            : %.3f s\n', ...
    confirmedAbsentSeconds);

fprintf('Recovery after device return    : %.3f s\n', ...
    recoveryAfterReturnSeconds);

if gatewayActiveThroughout

    fprintf('Gateway service during outage   : ACTIVE throughout\n');

else

    fprintf('Gateway service during outage   : NOT active throughout\n');

end

plotStart = ...
    tLastDataBefore - seconds(20);

plotEnd = ...
    tFirstRecovered + seconds(30);

plotA = ...
    A_time >= plotStart & ...
    A_time <= plotEnd;

A_time_plot = A_time(plotA);
A_seq_plot  = A_seq(plotA);

plotMonitor = ...
    monitorTime >= plotStart & ...
    monitorTime <= plotEnd;

monitorTimePlot = ...
    monitorTime(plotMonitor);

serialStatePlot = ...
    serialState(plotMonitor);

fig = figure( ...
    'Color','w', ...
    'Units','pixels', ...
    'Position',[100 70 1200 720]);

tl = tiledlayout( ...
    fig, ...
    2,1, ...
    'TileSpacing','compact', ...
    'Padding','compact');

ax1 = nexttile(tl,1);

hold(ax1,'on');

yMinimum = min(A_seq_plot) - 2;
yMaximum = max(A_seq_plot) + 2;

hShade1 = patch( ...
    ax1, ...
    [ ...
    tFirstAbsent ...
    tFirstPresentAfter ...
    tFirstPresentAfter ...
    tFirstAbsent ...
    ], ...
    [ ...
    yMinimum ...
    yMinimum ...
    yMaximum ...
    yMaximum ...
    ], ...
    [0.90 0.90 0.90], ...
    'EdgeColor','none', ...
    'FaceAlpha',0.65, ...
    'DisplayName','Serial interruption');

hSequence = plot( ...
    ax1, ...
    A_time_plot, ...
    A_seq_plot, ...
    '-o', ...
    'LineWidth',1.7, ...
    'MarkerSize',4.8, ...
    'Color',[0.0000 0.4470 0.7410], ...
    'MarkerFaceColor',[0.0000 0.4470 0.7410], ...
    'DisplayName','Sensor A records');

xline( ...
    ax1, ...
    tFirstAbsent, ...
    '--', ...
    'Color',[0.35 0.35 0.35], ...
    'LineWidth',1.1, ...
    'HandleVisibility','off');

xline( ...
    ax1, ...
    tFirstPresentAfter, ...
    '--', ...
    'Color',[0.35 0.35 0.35], ...
    'LineWidth',1.1, ...
    'HandleVisibility','off');

xline( ...
    ax1, ...
    tFirstRecovered, ...
    ':', ...
    'Color',[0.85 0.15 0.15], ...
    'LineWidth',1.3, ...
    'HandleVisibility','off');

plot( ...
    ax1, ...
    tLastDataBefore, ...
    seqLastBefore, ...
    's', ...
    'MarkerSize',6, ...
    'MarkerFaceColor','k', ...
    'MarkerEdgeColor','k', ...
    'HandleVisibility','off');

hRecovered = plot( ...
    ax1, ...
    tFirstRecovered, ...
    seqFirstRecovered, ...
    'o', ...
    'MarkerSize',7, ...
    'MarkerFaceColor',[0.90 0.10 0.10], ...
    'MarkerEdgeColor',[0.90 0.10 0.10], ...
    'DisplayName','First recovered DATA');

ylabel( ...
    ax1, ...
    'Sensor A sequence', ...
    'FontName','Times New Roman', ...
    'FontSize',13);

ylim(ax1,[yMinimum yMaximum]);

xlim(ax1,[plotStart plotEnd]);

grid(ax1,'on');
ax1.GridAlpha = 0.16;

box(ax1,'off');

ax1.FontName = 'Times New Roman';
ax1.FontSize = 11.5;
ax1.LineWidth = 1;

legend( ...
    ax1, ...
    [hSequence hShade1 hRecovered], ...
    { ...
    'Sensor A records', ...
    'Serial interruption', ...
    'First recovered DATA' ...
    }, ...
    'Location','southeast', ...
    'FontName','Times New Roman', ...
    'FontSize',10.5);

ax2 = nexttile(tl,2);

hold(ax2,'on');

hShade2 = patch( ...
    ax2, ...
    [ ...
    tFirstAbsent ...
    tFirstPresentAfter ...
    tFirstPresentAfter ...
    tFirstAbsent ...
    ], ...
    [-0.20 -0.20 1.20 1.20], ...
    [0.90 0.90 0.90], ...
    'EdgeColor','none', ...
    'FaceAlpha',0.65, ...
    'HandleVisibility','off');

stairs( ...
    ax2, ...
    monitorTimePlot, ...
    serialStatePlot, ...
    'LineWidth',2.0, ...
    'Color',[0.8500 0.3250 0.0980]);

xline( ...
    ax2, ...
    tFirstAbsent, ...
    '--', ...
    'Color',[0.35 0.35 0.35], ...
    'LineWidth',1.1, ...
    'HandleVisibility','off');

xline( ...
    ax2, ...
    tFirstPresentAfter, ...
    '--', ...
    'Color',[0.35 0.35 0.35], ...
    'LineWidth',1.1, ...
    'HandleVisibility','off');

xline( ...
    ax2, ...
    tFirstRecovered, ...
    ':', ...
    'Color',[0.85 0.15 0.15], ...
    'LineWidth',1.3, ...
    'HandleVisibility','off');

ylim(ax2,[-0.20 1.20]);

yticks(ax2,[0 1]);

yticklabels(ax2,{ ...
    'ABSENT', ...
    'PRESENT'});

ylabel( ...
    ax2, ...
    'USB serial state', ...
    'FontName','Times New Roman', ...
    'FontSize',13);

xlabel( ...
    ax2, ...
    'Gateway clock on 23 September 2026', ...
    'FontName','Times New Roman', ...
    'FontSize',12.5);

xlim(ax2,[plotStart plotEnd]);

grid(ax2,'on');
ax2.GridAlpha = 0.16;

box(ax2,'off');

ax2.FontName = 'Times New Roman';
ax2.FontSize = 11.5;
ax2.LineWidth = 1;

linkaxes([ax1 ax2],'x');

ax1.XTickLabel = [];

ax2.XAxis.TickLabelFormat = 'HH:mm:ss';

try
    ax1.XAxis.SecondaryLabel.Visible = 'off';
catch
end

try
    ax2.XAxis.SecondaryLabel.Visible = 'off';
catch
end

pngFile = fullfile( ...
    dataPath, ...
    'Figure_5_7_Gateway_Recovery.png');

pdfFile = fullfile( ...
    dataPath, ...
    'Figure_5_7_Gateway_Recovery.pdf');

exportgraphics( ...
    fig, ...
    pngFile, ...
    'Resolution',600);

exportgraphics( ...
    fig, ...
    pdfFile, ...
    'ContentType','vector');

fprintf('\n');
fprintf('========================================================\n');
fprintf('FINAL FIGURE EXPORTED\n');
fprintf('========================================================\n');

fprintf('PNG:\n%s\n\n',pngFile);

fprintf('PDF:\n%s\n\n',pdfFile);

fprintf('Done.\n');

end
